### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by harris**

### CODE REVIEW

**Comment by zhershds** [comment]
Hi, could you merge this change to master brunch? without that ZendeskAPI is not available.

**Comment by harris** [comment]
@zhershds I am not a maintainer so I have no permission to merge it.

**Comment by zhershds** [comment]
I see, it is mostly the request to owner of repository.

**Comment by ilyavas** [comment]
I have the same issue, would be nice if @B3nnyL find time to merge it :)

**Pull request merged**
